#%RAML 1.0 DataType

additionalProperties: false
properties:
  accountNum:
    type: string
    displayName: Account Number
  bankName:
    type: string
    displayName: Bank Name
  confirmContactNum:
    type: string
    displayName: contact number confirmation
  confirmEmail:
    type: string
    displayName: email confirmation
  policyNumber:
    type: string
    displayName: policy number
  quoteId:
    type: string
    displayName: quote id
  id?:
    type: string
    displayName: policy id
